[tool.poetry]
name = "fastapi-sqlalchemy-asyncpg"
version = "0.0.2"
description = ""
authors = ["Jakub Miazek <the@grillazz.com>"]
packages = []
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
alembic = "*"
asyncpg = "*"
httpx = "*"
pydantic = "*"
sqlalchemy = "*"
fastapi = "*"
uvicorn = { extras = ["standard"], version = "*" }
uvloop = "*"
httptools = "*"
rich = "*"
devtools = { extras = ["pygments"], version = "*" }
black = "*"
safety = "*"
pyupgrade = "*"
ipython = "*"
pytest-cov = "*"
pytest-asyncio = "*"
ruff = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120


select = ["E", "F", "U", "N", "C", "B"]
ignore = ["B008"]
# B008 - Do not perform function calls in argument defaults. https://github.com/tiangolo/fastapi/issues/1522

# Exclude a variety of commonly ignored directories.
exclude = [
    "alembic",
]
# Assume Python 3.10.
target-version = "py310"

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
